# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Category List Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'RealmSwift'
	pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.2'

  # Pods for Category List Demo

  target 'Category List DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Category List DemoUITests' do
    # Pods for testing
  end

end
